import type { StepDefinition } from "../workflow-engine.js";

export const prStep: StepDefinition = {
  name: "pr",
  allowedTools: ["Bash", "Read", "Glob"],
  resumeFromPrevious: true,
  buildPrompt: (task, repo) => {
    const nightcodeUrl = task.nightcodeUrl;

    // Build PR body programmatically so Claude just needs to fill in the summary
    const planSection = task.stepResults.plan
      ? `\n<details>\n<summary>Implementation Plan</summary>\n\n${task.stepResults.plan}\n\n</details>\n`
      : "";

    const auditSection = task.stepResults.audit
      ? `\n<details>\n<summary>Code Audit</summary>\n\n${task.stepResults.audit}\n\n</details>\n`
      : "";

    const skillsSection = task.kavelaSkills.length > 0
      ? `\n## Context Loaded\nThe following team knowledge was loaded from [Kavela](https://kavela.ai) before implementation:\n${task.kavelaSkills.map(s => `- ${s}`).join("\n")}\n`
      : "";

    return `You MUST create a GitHub pull request using the gh CLI. Follow these steps EXACTLY:

## Step 1: Stage and commit
Run these commands:
\`\`\`bash
git add -A
git diff --cached --stat
\`\`\`
Then commit with a descriptive message.

## Step 2: Push the branch
\`\`\`bash
git push -u origin ${task.branchName}
\`\`\`

## Step 3: Create the PR using gh CLI
You MUST use \`gh pr create\` — do NOT just push and stop. Run:
\`\`\`bash
gh pr create --title "<TITLE>" --body "<BODY>" --base ${repo.branch}
\`\`\`

The title should be concise (under 70 chars) and describe what changed.

The body MUST be a single string passed to --body. Structure it with these sections:

## Summary
- (2-3 bullet points of what changed and why)

## Changes
- (list each file modified with a brief description)

## Key Decisions
- (explain architectural choices, tradeoffs, why you chose this approach)
${planSection ? "\n## Plan\n(include the implementation plan in a collapsed <details> block)" : ""}
${auditSection ? "\n## Audit\n(include audit findings in a collapsed <details> block)" : ""}
${skillsSection ? "\nInclude this Context Loaded section in the PR body:\n" + skillsSection : ""}

## nightcode
[View task details](${nightcodeUrl}/tasks/${task.id}) · [Refine this task](${nightcodeUrl}/tasks/${task.id})

## How to continue
To pick up where this automated session left off:
\\\`\\\`\\\`bash
claude --from-pr <THIS_PR_URL>
\\\`\\\`\\\`

---
*Generated by [nightcode](https://github.com/kavela-app/nightcode)*

IMPORTANT: You MUST actually run the \`gh pr create\` command. The output should contain a URL like https://github.com/.../pull/123. If gh pr create fails, debug and retry. Do NOT stop after just pushing.

## Task context
Title: ${task.title}
${task.prompt}`;
  },
  systemPrompt: (repo) => {
    let sys = `You are creating a pull request. Base branch is "${repo.branch}".

CRITICAL RULES:
1. You MUST run \`gh pr create\` — NOT draft, a real PR
2. Do NOT just push the branch and stop — that is NOT creating a PR
3. The PR body must contain a Summary, Changes, Key Decisions, and How to continue sections
4. If \`gh pr create\` fails, check the error and fix it (auth issues, conflicts, etc.)
5. The final output MUST contain the PR URL (https://github.com/.../pull/NUMBER)`;
    if (repo.systemPrompt) {
      sys = `${repo.systemPrompt}\n\n${sys}`;
    }
    return sys;
  },
};
