import type { StepDefinition } from "../workflow-engine.js";

export const prStep: StepDefinition = {
  name: "pr",
  allowedTools: ["Bash", "Read", "Glob"],
  resumeFromPrevious: true,
  buildPrompt: (task) => {
    // Build the PR body content from step results
    let prBodySections = "";

    if (task.stepResults.plan) {
      prBodySections += `
Include the following plan in the PR body under a "## Plan" section (use a <details> tag so it's collapsed by default):

<details>
<summary>Implementation Plan</summary>

${task.stepResults.plan}

</details>
`;
    }

    if (task.stepResults.audit) {
      prBodySections += `
Also include the audit findings under "## Audit" (also collapsed):

<details>
<summary>Code Audit</summary>

${task.stepResults.audit}

</details>
`;
    }

    return `Create a pull request for the changes you made.

## Instructions
1. Stage all changed files: \`git add -A\`
2. Create a commit with a clear, descriptive message summarizing what was done
3. Push the branch to origin: \`git push -u origin ${task.branchName || "HEAD"}\`
4. Create a PR (NOT draft) using gh CLI:
   \`\`\`
   gh pr create --title "..." --body "..." --base "${task.branchName ? "" : "main"}"
   \`\`\`
5. The PR title should be concise (under 70 chars)
6. The PR body MUST include these sections in this exact order:
   - **## Summary** — 2-3 bullet points of what changed and why
   - **## Changes** — list of files modified with brief description of each change
   ${prBodySections ? "- The plan/audit sections described below" : ""}
   - **## How to continue** — include this exact block:
     \`\`\`
     ## How to continue

     To pick up where this automated session left off, run:
     \\\`\\\`\\\`bash
     claude --from-pr <PR_URL>
     \\\`\\\`\\\`
     \`\`\`
   - At the very bottom: "---\\n*Generated by [nightcode](https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/nightcode)*"
${prBodySections}
## Task context
Title: ${task.title}
${task.prompt}`;
  },
  systemPrompt: (repo) => {
    let sys = `You are creating a pull request. Base branch is "${repo.branch}". Create a REAL PR (not draft) so reviewers can see it immediately.`;
    if (repo.systemPrompt) {
      sys = `${repo.systemPrompt}\n\n${sys}`;
    }
    return sys;
  },
};
